apiVersion: apps/v1
kind: Deployment
metadata:
  name: boookmyshow-app
  labels:
    app: bookmyshow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
        - name: bookmyshow-container
          image: meteorshower471/bookmyshow:latest
          ports:
            - containerPort: 80
